import React, { useState } from 'react';
import { 
  Sparkles, 
  Palette, 
  Bug, 
  ShieldAlert, 
  Zap, 
  ArrowLeft, 
  Copy, 
  Check, 
  Clock, 
  Search, 
  Download, 
  Printer, 
  FileCode, 
  GitCommit, 
  Award,
  Layers
} from 'lucide-react';
import HealthRadar from './HealthRadar';

export default function ResultsView({ reviewData, onBackToForm }) {
  const [activeTab, setActiveTab] = useState('all');
  const [searchQuery, setSearchQuery] = useState('');
  const [highlightedLine, setHighlightedLine] = useState(null);
  const [copiedPr, setCopiedPr] = useState(false);
  const [copiedPatchIdx, setCopiedPatchIdx] = useState(null);

  if (!reviewData) return null;

  const { 
    id, 
    source_url, 
    code_snippet = '', 
    language = 'auto', 
    health_score = { score: 100, grade: 'A+', style_score: 100, bug_score: 100, security_score: 100, performance_score: 100 }, 
    style = [], 
    bugs = [], 
    security = [], 
    performance = [], 
    summary = '', 
    created_at 
  } = reviewData;

  const totalFindings = style.length + bugs.length + security.length + performance.length;
  const criticalSecCount = security.filter(s => ['critical', 'high'].includes(s.severity?.toLowerCase())).length;

  const allFindings = [
    ...security.map(item => ({ ...item, category: 'security', categoryLabel: 'AppSec Risk', icon: ShieldAlert, color: 'rose' })),
    ...bugs.map(item => ({ ...item, category: 'bug', categoryLabel: 'Logic Flaw', icon: Bug, color: 'amber' })),
    ...performance.map(item => ({ ...item, category: 'perf', categoryLabel: 'Performance', icon: Zap, color: 'emerald' })),
    ...style.map(item => ({ ...item, category: 'style', categoryLabel: 'Style / Lint', icon: Palette, color: 'purple' })),
  ];

  const filteredFindings = allFindings.filter(f => {
    if (activeTab !== 'all' && f.category !== activeTab) return false;
    if (!searchQuery.trim()) return true;
    const q = searchQuery.toLowerCase();
    return (
      (f.issue && f.issue.toLowerCase().includes(q)) ||
      (f.suggestion && f.suggestion.toLowerCase().includes(q)) ||
      (f.line && f.line.toLowerCase().includes(q)) ||
      (f.cwe_id && f.cwe_id.toLowerCase().includes(q))
    );
  });

  const handleCopyPrComment = () => {
    let prComment = `## 🤖 AI Multi-Agent Code Review Report\n\n`;
    prComment += `**Overall Health Score**: \`${health_score.score}/100 (Grade ${health_score.grade})\`\n\n`;
    prComment += `### Summary\n${summary}\n\n`;
    prComment += `### Findings Breakdown\n`;
    prComment += `- 🎨 **Style & PEP8**: ${style.length} issue(s)\n`;
    prComment += `- 🐛 **Logic Bugs**: ${bugs.length} flaw(s)\n`;
    prComment += `- 🛡️ **AppSec Vulnerabilities**: ${security.length} risk(s)\n`;
    prComment += `- ⚡ **Performance**: ${performance.length} optimization(s)\n\n`;
    prComment += `*Generated by CodeReviewPro Platform*`;

    navigator.clipboard.writeText(prComment);
    setCopiedPr(true);
    setTimeout(() => setCopiedPr(false), 2000);
  };

  const handleCopyPatch = (idx, text) => {
    navigator.clipboard.writeText(text);
    setCopiedPatchIdx(idx);
    setTimeout(() => setCopiedPatchIdx(null), 2000);
  };

  const handleExportJson = () => {
    const dataStr = "data:text/json;charset=utf-8," + encodeURIComponent(JSON.stringify(reviewData, null, 2));
    const downloadAnchor = document.createElement('a');
    downloadAnchor.setAttribute("href", dataStr);
    downloadAnchor.setAttribute("download", `code_review_${id}.json`);
    document.body.appendChild(downloadAnchor);
    downloadAnchor.click();
    downloadAnchor.remove();
  };

  const codeLines = code_snippet ? code_snippet.split('\n') : [];

  return (
    <div className="max-w-6xl mx-auto space-y-6">
      {/* Top Action Bar */}
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 pb-3 border-b border-[var(--border-subtle)]">
        <button
          onClick={onBackToForm}
          className="flex items-center gap-2 px-3.5 py-1.5 rounded-lg theme-panel text-[var(--text-secondary)] hover:text-[var(--text-primary)] text-xs font-bold transition-colors"
        >
          <ArrowLeft className="w-3.5 h-3.5" />
          Back to Workbench
        </button>

        <div className="flex flex-wrap items-center gap-2.5">
          <button
            onClick={handleCopyPrComment}
            className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-indigo-600/10 text-indigo-500 border border-indigo-500/30 text-xs font-bold hover:bg-indigo-600/20 transition-colors"
          >
            {copiedPr ? <Check className="w-3.5 h-3.5 text-emerald-500" /> : <Copy className="w-3.5 h-3.5" />}
            {copiedPr ? 'PR Comment Copied!' : 'Copy GitHub PR Comment'}
          </button>

          <button
            onClick={handleExportJson}
            className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg theme-panel text-[var(--text-secondary)] hover:text-[var(--text-primary)] text-xs font-bold transition-colors"
          >
            <Download className="w-3.5 h-3.5" />
            JSON
          </button>

          <button
            onClick={() => window.print()}
            className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg theme-panel text-[var(--text-secondary)] hover:text-[var(--text-primary)] text-xs font-bold transition-colors"
          >
            <Printer className="w-3.5 h-3.5" />
            Print / PDF
          </button>
        </div>
      </div>

      {/* Executive Command Center */}
      <div className="grid grid-cols-1 md:grid-cols-12 gap-4">
        {/* Health Score Dial */}
        <div className="md:col-span-4 theme-panel p-5 rounded-2xl flex items-center justify-between gap-4">
          <div>
            <div className="text-[10px] uppercase font-bold text-[var(--text-muted)] tracking-wider">Health Index</div>
            <div className="text-2xl font-extrabold text-[var(--text-primary)] mt-1 flex items-center gap-2">
              {health_score.score} / 100
              <span className={`text-xs px-2 py-0.5 rounded-full font-bold font-mono ${
                health_score.score >= 88 ? 'bg-emerald-500/10 text-emerald-500 border border-emerald-500/20' :
                health_score.score >= 68 ? 'bg-indigo-500/10 text-indigo-500 border border-indigo-500/20' :
                'bg-rose-500/10 text-rose-500 border border-rose-500/20'
              }`}>
                Grade {health_score.grade}
              </span>
            </div>
            <p className="text-[10px] text-[var(--text-muted)] mt-1 font-mono">Weighted 4-Agent Score</p>
          </div>

          <HealthRadar healthScore={health_score} />
        </div>

        {/* 3 Metric Cards */}
        <div className="md:col-span-8 grid grid-cols-1 sm:grid-cols-3 gap-3">
          <div className="theme-panel p-4 rounded-2xl space-y-1">
            <div className="text-[10px] uppercase font-bold text-[var(--text-muted)] tracking-wider flex items-center justify-between">
              <span>Security Risks</span>
              <ShieldAlert className="w-3.5 h-3.5 text-rose-500" />
            </div>
            <div className="text-xl font-bold text-[var(--text-primary)] font-mono">{security.length} Findings</div>
            <p className="text-[10px] text-[var(--text-muted)]">{criticalSecCount > 0 ? `${criticalSecCount} High/Critical Risks` : '0 Critical Risks'}</p>
          </div>

          <div className="theme-panel p-4 rounded-2xl space-y-1">
            <div className="text-[10px] uppercase font-bold text-[var(--text-muted)] tracking-wider flex items-center justify-between">
              <span>Bugs & Edge Cases</span>
              <Bug className="w-3.5 h-3.5 text-amber-500" />
            </div>
            <div className="text-xl font-bold text-[var(--text-primary)] font-mono">{bugs.length} Issues</div>
            <p className="text-[10px] text-[var(--text-muted)]">Logic & unhandled cases</p>
          </div>

          <div className="theme-panel p-4 rounded-2xl space-y-1">
            <div className="text-[10px] uppercase font-bold text-[var(--text-muted)] tracking-wider flex items-center justify-between">
              <span>Est. Remediation</span>
              <Clock className="w-3.5 h-3.5 text-emerald-500" />
            </div>
            <div className="text-xl font-bold text-[var(--text-primary)] font-mono">~{totalFindings * 5 || 5} Mins</div>
            <p className="text-[10px] text-[var(--text-muted)]">Estimated developer fix effort</p>
          </div>
        </div>
      </div>

      {/* Staff PR Executive Summary */}
      <div className="theme-panel rounded-2xl p-5 border-indigo-500/20 space-y-3">
        <div className="flex items-center gap-2 text-xs font-bold text-indigo-500 border-b border-[var(--border-subtle)] pb-2">
          <Sparkles className="w-4 h-4 text-amber-500" />
          <span>Staff Engineer PR Review Executive Summary</span>
        </div>
        <div className="text-xs text-[var(--text-primary)] leading-relaxed whitespace-pre-line space-y-2">
          {summary || 'Review completed successfully.'}
        </div>
      </div>

      {/* Main Review Section: Code Inspector & Filterable Findings */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Left: Code Inspector Window */}
        <div className="lg:col-span-6 space-y-2">
          <div className="flex items-center justify-between text-xs text-[var(--text-secondary)]">
            <span className="font-bold text-[var(--text-primary)] uppercase text-[11px] flex items-center gap-1.5">
              <FileCode className="w-3.5 h-3.5 text-indigo-500" />
              Source Code Inspector
            </span>
            <span className="font-mono text-[11px] text-[var(--text-muted)]">{codeLines.length} lines • {language.toUpperCase()}</span>
          </div>

          <div className="rounded-2xl border border-[var(--border-subtle)] bg-[var(--bg-editor)] overflow-hidden max-h-[560px] overflow-y-auto">
            <div className="flex font-mono text-xs">
              {/* Line Gutter */}
              <div className="code-line-gutter py-3 select-none border-r border-[var(--border-subtle)] shrink-0">
                {codeLines.map((_, i) => (
                  <div 
                    key={i} 
                    className={`leading-5 cursor-pointer hover:text-indigo-500 ${highlightedLine === (i + 1) ? 'text-indigo-500 font-bold' : ''}`}
                    onClick={() => setHighlightedLine(i + 1)}
                  >
                    {i + 1}
                  </div>
                ))}
              </div>

              {/* Code Content */}
              <div className="py-3 px-3 flex-1 overflow-x-auto">
                {codeLines.map((line, i) => {
                  const lineNum = i + 1;
                  const isHighlighted = highlightedLine === lineNum;
                  return (
                    <div 
                      key={i} 
                      className={`leading-5 whitespace-pre ${isHighlighted ? 'bg-indigo-500/15 text-indigo-500 -mx-3 px-3 font-semibold' : 'text-[var(--text-primary)]'}`}
                    >
                      {line || ' '}
                    </div>
                  );
                })}
              </div>
            </div>
          </div>
        </div>

        {/* Right: Finding Details & Git Diff Fixes */}
        <div className="lg:col-span-6 space-y-3">
          {/* Finding Filter Tabs */}
          <div className="flex flex-wrap items-center justify-between gap-2 border-b border-[var(--border-subtle)] pb-2">
            <div className="flex items-center gap-1">
              <button
                onClick={() => setActiveTab('all')}
                className={`px-2.5 py-1 rounded-lg text-xs font-bold transition-colors ${
                  activeTab === 'all' ? 'bg-indigo-600 text-white' : 'text-[var(--text-secondary)] hover:text-[var(--text-primary)]'
                }`}
              >
                All ({allFindings.length})
              </button>
              <button
                onClick={() => setActiveTab('security')}
                className={`px-2.5 py-1 rounded-lg text-xs font-bold transition-colors ${
                  activeTab === 'security' ? 'bg-rose-600 text-white' : 'text-[var(--text-secondary)] hover:text-[var(--text-primary)]'
                }`}
              >
                AppSec ({security.length})
              </button>
              <button
                onClick={() => setActiveTab('bug')}
                className={`px-2.5 py-1 rounded-lg text-xs font-bold transition-colors ${
                  activeTab === 'bug' ? 'bg-amber-600 text-white' : 'text-[var(--text-secondary)] hover:text-[var(--text-primary)]'
                }`}
              >
                Bugs ({bugs.length})
              </button>
              <button
                onClick={() => setActiveTab('perf')}
                className={`px-2.5 py-1 rounded-lg text-xs font-bold transition-colors ${
                  activeTab === 'perf' ? 'bg-emerald-600 text-white' : 'text-[var(--text-secondary)] hover:text-[var(--text-primary)]'
                }`}
              >
                Perf ({performance.length})
              </button>
              <button
                onClick={() => setActiveTab('style')}
                className={`px-2.5 py-1 rounded-lg text-xs font-bold transition-colors ${
                  activeTab === 'style' ? 'bg-purple-600 text-white' : 'text-[var(--text-secondary)] hover:text-[var(--text-primary)]'
                }`}
              >
                Style ({style.length})
              </button>
            </div>
          </div>

          {/* Finding Search */}
          <div className="relative">
            <Search className="w-3.5 h-3.5 text-[var(--text-muted)] absolute left-3 top-2.5" />
            <input
              type="text"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              placeholder="Search findings by keyword, line, or CWE ID..."
              className="w-full pl-9 pr-3 py-1.5 theme-panel rounded-lg text-xs text-[var(--text-primary)] placeholder-[var(--text-muted)] focus:outline-none focus:border-indigo-500"
            />
          </div>

          {/* Finding Cards List */}
          <div className="space-y-3 max-h-[480px] overflow-y-auto pr-1">
            {filteredFindings.length === 0 ? (
              <div className="p-8 text-center text-xs text-[var(--text-muted)] theme-panel rounded-2xl">
                No issues found matching current filters.
              </div>
            ) : (
              filteredFindings.map((item, idx) => {
                const Icon = item.icon;
                return (
                  <div 
                    key={idx} 
                    className="theme-card p-4 rounded-2xl space-y-2.5 transition-colors"
                  >
                    <div className="flex items-center justify-between gap-2">
                      <div className="flex items-center gap-2">
                        <span className={`p-1 rounded bg-${item.color}-500/10 text-${item.color}-500`}>
                          <Icon className="w-3.5 h-3.5" />
                        </span>
                        <span className="text-xs font-bold text-[var(--text-primary)] font-mono">{item.line || 'Global'}</span>
                        {item.cwe_id && (
                          <span className="px-2 py-0.5 rounded text-[10px] font-mono font-bold bg-rose-500/10 text-rose-500 border border-rose-500/20">
                            {item.cwe_id}
                          </span>
                        )}
                      </div>

                      {item.severity && (
                        <span className={`px-2 py-0.5 rounded text-[10px] font-bold font-mono uppercase ${
                          item.severity === 'high' || item.severity === 'critical' ? 'bg-rose-500/10 text-rose-500 border border-rose-500/20' :
                          item.severity === 'medium' ? 'bg-amber-500/10 text-amber-500 border border-amber-500/20' : 'bg-emerald-500/10 text-emerald-500 border border-emerald-500/20'
                        }`}>
                          {item.severity}
                        </span>
                      )}
                    </div>

                    <p className="text-xs text-[var(--text-primary)] font-medium leading-relaxed">{item.issue}</p>

                    {/* Git-Style Diff Patch Box */}
                    {item.suggestion && (
                      <div className="rounded-xl border border-[var(--border-subtle)] bg-[var(--bg-editor)] text-xs font-mono overflow-hidden">
                        <div className="flex items-center justify-between px-3 py-1.5 theme-panel border-b border-[var(--border-subtle)] text-[10px] text-[var(--text-secondary)]">
                          <span className="font-bold text-indigo-500 flex items-center gap-1.5">
                            <GitCommit className="w-3 h-3 text-indigo-500" />
                            Suggested Fix / Remediation Patch
                          </span>
                          <button
                            type="button"
                            onClick={() => handleCopyPatch(idx, item.suggestion)}
                            className="text-indigo-500 hover:text-indigo-400 flex items-center gap-1"
                          >
                            {copiedPatchIdx === idx ? <Check className="w-3 h-3 text-emerald-500" /> : <Copy className="w-3 h-3" />}
                            {copiedPatchIdx === idx ? 'Copied' : 'Copy Fix'}
                          </button>
                        </div>
                        <div className="p-3 text-[11px] text-[var(--text-primary)] whitespace-pre-wrap leading-relaxed">
                          {item.suggestion}
                        </div>
                      </div>
                    )}
                  </div>
                );
              })
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
